### ISSUE TITLE
Hitting start button multiple times causes game to speed up

### ISSUE THREAD

**Issue by ToniRib** [ToniRib/game_time#23]
Once you start the game, if you hit the start button again it will speed up the enemies. I have no idea why this is happening, but we probably want to disable the start button after you press it once.

**Comment by Jlawlzz** [comment]
I think disabling the start button is the right move here.  It seems plausible that the problem stems for every time you hit the start button, it begins a second gameLoop function that runs the same processes, but twice as fast.
